apiVersion: backstage.io/v1alpha1
kind: {{ values.kind }}
metadata:
  name: {{ values.componentName }}
  description: {{ values.description }}
  annotations:
    github.com/project-slug: Infosys/{{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: {{ values.type }}
  lifecycle: {{ values.lifecycle }}
  owner: {{ values.owner }}
  ownedBy:
{{#each values.ownedBy}}
    - {{this}}
{{/each}}
{{#if values.dependencies}}
  dependsOn:
{{#each values.dependencies}}
    - {{this}}
{{/each}}
{{/if}}
