site_name: 'OpenFGA Backstage Plugin'
docs_dir: docs
repo_url: https://github.com/Infosys/openfga-plugin-backstage
plugins:
  - techdocs-core

nav:
  - Overview:
      - What is OpenFGA Backstage Plugin?: 'index.md'
      - How to install the OpenFGA plugin?: 'openfgaplugin.md'
